# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: musician_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'musician_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16musician_service.proto\x12\x08musician\"\xf6\x01\n\x0e\x43ontrolMessage\x12\x1e\n\x04ping\x18\x01 \x01(\x0b\x32\x0e.musician.PingH\x00\x12\x1e\n\x04pong\x18\x02 \x01(\x0b\x32\x0e.musician.PongH\x00\x12\x1e\n\x04task\x18\x03 \x01(\x0b\x32\x0e.musician.TaskH\x00\x12&\n\x06result\x18\x04 \x01(\x0b\x32\x14.musician.TaskResultH\x00\x12+\n\x0block_status\x18\x05 \x01(\x0b\x32\x14.musician.LockStatusH\x00\x12\'\n\x05\x65rror\x18\x06 \x01(\x0b\x32\x16.musician.ErrorMessageH\x00\x42\x06\n\x04kind\"%\n\x04Ping\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"9\n\x04Pong\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x12\n\nlatency_ms\x18\x03 \x01(\x03\"$\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x63sv_data\x18\x02 \x01(\t\"5\n\nTaskResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0b\n\x03log\x18\x03 \x01(\t\"I\n\nLockStatus\x12\x13\n\x0bmusician_id\x18\x01 \x01(\t\x12\x0e\n\x06locked\x18\x02 \x01(\x08\x12\x16\n\x0elocked_by_task\x18\x03 \x01(\t\"\"\n\x0c\x45rrorMessage\x12\x12\n\nerror_text\x18\x01 \x01(\t2T\n\x0fMusicianService\x12\x41\n\x07\x43onnect\x12\x18.musician.ControlMessage\x1a\x18.musician.ControlMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'musician_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTROLMESSAGE']._serialized_start=37
  _globals['_CONTROLMESSAGE']._serialized_end=283
  _globals['_PING']._serialized_start=285
  _globals['_PING']._serialized_end=322
  _globals['_PONG']._serialized_start=324
  _globals['_PONG']._serialized_end=381
  _globals['_TASK']._serialized_start=383
  _globals['_TASK']._serialized_end=419
  _globals['_TASKRESULT']._serialized_start=421
  _globals['_TASKRESULT']._serialized_end=474
  _globals['_LOCKSTATUS']._serialized_start=476
  _globals['_LOCKSTATUS']._serialized_end=549
  _globals['_ERRORMESSAGE']._serialized_start=551
  _globals['_ERRORMESSAGE']._serialized_end=585
  _globals['_MUSICIANSERVICE']._serialized_start=587
  _globals['_MUSICIANSERVICE']._serialized_end=671
# @@protoc_insertion_point(module_scope)
